#sonar-project.properties

sonar.projectKey=s225369303_8.2CDevSecOps
sonar.organization=s225369303
sonar.host.url=https://sonarcloud.io
sonar.login=${efe7cda07b75e4254394ab02fdb8e2b22f25983e}

sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8